name="GPGKeychain"
appName="GPG Keychain.app"

pkgProj_corename="GPGKeychain_Core.pkgproj"
pkgCoreName="GPGKeychain_Core.pkg"
pkgProj_name="GPGKeychain.pkgproj"
pkgName="GPGKeychain.pkg"

imgBackground="Installer/background_dmg.png"
localizeDir="Installer/localized"
volumeName="GPG Keychain.localized"
volumeLayout="Installer/DS_Store"
pkgPos="290,220"

sshKeyname="Sparkle GPGKeychain - Private key"


unset REVISION PRERELEASE
MAJOR=1
MINOR=2
#REVISION=0
PRERELEASE=a4

source "$(dirname "${BASH_SOURCE[0]}")/Dependencies/GPGTools_Core/newBuildSystem/versioning.sh"
