name="GPG Keychain Access"
appName="GPG Keychain Access.app"

imgBackground="Installer/Background.png"
localizeDir="Installer/localized"
volumeName="GPG Keychain Access.localized"
volumeLayout="Installer/DS_Store"
pkgPos="290, 220"

sshKeyname="Sparkle GPGKeychainAccess - Private key"


unset REVISION PRERELEASE
MAJOR=1
MINOR=0
#REVISION=1
#PRERELEASE=b8

source "$(dirname "${BASH_SOURCE[0]}")/Dependencies/GPGTools_Core/newBuildSystem/versioning.sh"
