name="GPG Keychain Access"
appName="GPG Keychain Access.app"
html="keychain"
appsLink=1
imgBackground="dmgResources/Background.png"
dmgUrl="GPGTools/GPGKeychainAccess"
downloadUrlPrefix="https://github.com/downloads/GPGTools/GPGKeychainAccess/"
sshKeyname="Sparkle GPGKeychainAccess - Private key"
appPos="160, 130"
iconSize=128
localizeDir="dmgResources/localized"
volumeName="GPG Keychain Access.localized"
volumeLayout="Installer/DS_Store"
pkgProj_dir="Installer"
pkgProj_corename="GPGKeychainAccess_Core.pkgproj"
pkgProj_core="${pkgProj_dir}/${pkgProj_corename}"

MAJOR_VERSION=1
MINOR_VERSION=0
#PRERELEASE_VERSION=b8

version=${MAJOR_VERSION}.${MINOR_VERSION}${PRERELEASE_VERSION}
build_version="`git log -1 --pretty=format:%h`"
build_dir="build/"
